# Docker Compose version 2
version: "2"
services:
  # application tier container
  app:
    restart: always
    # Use the version 1 image in the private registry
    image: app:latest
    ports:
      - "80:8080"
    # Ensure the app container starts after app-db
    depends_on:
      - app-db
  # database tier container
  app-db:
    restart: always
    volumes:
      # mount volume for database files
      - app-db:/data/db
    image: mongo:3
volumes:
  app-db: