version: "2.4" # Menggunakan Docker Compose versi 2 atau lebih

services:
  item-db:
    image: mongo:3 # Menggunakan image MongoDB versi 3 dari Docker Hub
    volumes:
      - app-db:/data/db # Menggunakan volume bernama app-db dengan target /data/db di dalam container
    restart: always # Menerapkan restart policy agar container selalu restart jika terhenti

  item-app:
    image: ghcr.io/frisyk/microservices:v1 # Ganti dengan format GitHub Packages
    ports:
      - "80:8080" # Melakukan port mapping agar aplikasi dapat diakses melalui port 80 di host
    depends_on:
      - item-db # Memastikan item-app hanya berjalan setelah item-db diluncurkan
    restart: always # Menerapkan restart policy agar container selalu restart jika terhenti

volumes:
  app-db: # Mendefinisikan volume bernama app-db
